name: class
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - pip
  - pip:
    - matplotlib
    - numpy
    - pandas
    - plotly
    - scikit-learn
 # - python=3.9
#  - r-base=4.1.2
 # - r-dplyr
 # - r-ggplot2
 # - r-tidyverse
 # - r-reshape2
 # - r-plotly
 # - r-stringr
 # - pip
 # - pip:
 #   - matplotlib
 #   - numpy
 #   - pandas
 #   - plotly
 #   - scikit-learn
  
